# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('appointment_time', models.TimeField(default=django.utils.timezone.now)),
                ('appointment_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
